{{- if .Values.preUpgradeChart.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fid.fullname" . }}-delete-resources-sa
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
    "argocd.argoproj.io/hook": PreSync
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded,HookFailed,BeforeHookCreation
{{- end }}
