{{- /* Only include auto-config-promotion secret if the feature exists and is enabled */ -}}
{{- if hasKey .Values "autoConfigPromotion" }}
{{- if .Values.autoConfigPromotion.enabled }}
{{- include "fid.auto_config.promotion.validate" . -}}
{{- if not (hasKey .Values.autoConfigPromotion.git.credentials "secretName") }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "fid.auto_config.promotion.secret_name" . }}"
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  GIT_PRIVATE_KEY: {{ include "fid.auto_config.promotion.private_key" . | trim }}
  GIT_USERNAME: {{ include "fid.auto_config_promotion.git_username" . | trim }}
  GIT_PASSWORD: {{ include "fid.auto_config_promotion.git_password" . | trim }}
{{- end }}
{{- end }}
{{- end }}