{{- if semverCompare ">=8.1-0" (.Values.image.tag | default .Chart.AppVersion) -}}
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  AUTHENTICATION_PROVIDER: bGRhcA==
  TOKEN_PROVIDER: bGRhcA==
  TOKEN_STORAGE_PROVIDER: ZmlkU3RvcmFnZVByb3ZpZGVy
  TOKEN_ISSUER: cmFkaWFudGxvZ2lj
  AUTH_SECRET: cmFkaWFudGxvZ2ljc2VjcmV0
{{- end }}