{{- if and (not .Values.fid.sealedSecrets) (not .Values.sealedSecrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: rootcreds-{{ template "fid.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.fid.rootUser }}
  fid-root-username: {{ .Values.fid.rootUser | b64enc | quote }}
  {{- end }}
  {{- if .Values.fid.rootPassword }}
  fid-root-password: {{ .Values.fid.rootPassword | b64enc | quote }}
  {{- else }}
  fid-root-password: {{ randAlphaNum 12 | b64enc | quote }}
  {{- end }}
  {{- if .Values.zk.userName }}
  zk-username: {{ .Values.zk.userName | b64enc | quote }}
  {{- end }}
  {{- if .Values.zk.password }}
  zk-password: {{ .Values.zk.password | b64enc | quote }}
  {{- else }}
  zk-password: {{ randAlphaNum 12 | b64enc | quote }}
  {{- end }}
  {{- if .Values.fid.license }}
  fid-license: {{ .Values.fid.license | b64enc | quote }}
  {{- end }}
  {{- if .Values.fid.adminApiKey }}
  fid-admin-api-key: {{ .Values.fid.adminApiKey | b64enc | quote }}
  {{- else }}
  {{- if not .Release.IsUpgrade }}
  fid-admin-api-key: {{ randAlphaNum 32 | b64enc | quote }}
  {{- else }}
  {{- $secretName := (printf "%s-%s" "rootcreds" ( include "fid.fullname" . )) }}
  {{- $fidadminApiKey := index (lookup "v1" "Secret" .Release.Namespace $secretName ).data "fid-admin-api-key" }}
  {{- if $fidadminApiKey }}
  fid-admin-api-key: {{ $fidadminApiKey }}
  {{- else }}
  fid-admin-api-key: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
