{{- $targetTag := (.Values.image.tag | default .Chart.AppVersion) -}}
{{- $targetMajor := (index (splitList "." (index (splitList "-" $targetTag) 0)) 0) -}}
{{- if eq $targetMajor "9" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "fid.fullname" . }}-hdap-migration-rb
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: hdap-migration
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
    "argocd.argoproj.io/hook": PreSync
    "argocd.argoproj.io/sync-wave": "-5"
    "argocd.argoproj.io/hook-delete-policy": BeforeHookCreation
subjects:
  - kind: ServiceAccount
    name: {{ include "fid.fullname" . }}-hdap-migration-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "fid.fullname" . }}-hdap-migration-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
